### ISSUE TITLE
Error in WalletConnect Hedera Integration: "INVALID_SIGNATURE" on executeTransaction

### ISSUE THREAD

**Issue by soharang** [hashgraph/hedera-wallet-connect#117]
Hello, I am a wallet developer and I am developing a Hedera WalletConnect for Android/iOS environments, referencing the guide below:
https://specs.walletconnect.com/2.0/blockchain-rpc/hedera-rpc#hedera_signtransaction

The issue arises during testing on https://wc.hgraph.app/ where the signature map created via signTransaction from my wallet results in an "INVALID_SIGNATURE" error when executeTransaction is performed.

**To Reproduce** Steps to reproduce the behavior:

1. Go to 'https://wc.hgraph.app/'
2. Input necessary field and process "Initialize WalletConnect"
3. Click "Open WalletConnect Modal" and connect with my wallet (based on hedera-sdk-java for Android, or hedera-protobufs-swift for iOS)
4. Input necessary field and process "6. hedera_signTransaction".
    - My code for signTransaction:
        ```js
        byte[] base64DecodedTxBodyBytes = Base64.decode(transactionBody, Base64.DEFAULT);
        TransactionBody txBody = TransactionBody.parseFrom(base64DecodedTxBodyBytes);
        byte[] signature = privateKey.sign(txBody.toByteArray()); // privatekey for signer
        String signatureHexString = Numeric.toHexStringNoPrefix(signature);
        SignatureMap sigMap = SignatureMap.newBuilder()
                .addSigPair(SignaturePair.newBuilder()
                    .setEd25519(ByteString.fromHex(signatureHexString))
                    .setPubKeyPrefix(ByteString.fromHex(publicKey)).build()) / / publicKey : my public key string for signer
            .build();
        String base64Sigmap = new String(Base64.encode(sigMap.toByteArray(), Base64.NO_WRAP), "UTF-8");
        resultObject.put("signatureMap", base64Sigmap);
        ```

    - Now I get a result as below with success popup:
        ```
        {
            "params": {
                "signerAccountId": "hedera:testnet:0.0.741192",
                "transactionBody": "ChoKDAjnp4mxBhCx/OalARIICAAQABjIni0YABIGCAAQABgDGIDC1y8iAgh4MgByJAoiCg8KCAgAEAAYyJ4tEM8PGAAKDwoICAAQABj6ni0Q0A8YAA=="
            },
            "signatureMap": "CnAKLDAqMAUGAytlcAMhAHh6CY/kiByrJG8EW2q98oShnIRj5u6wjLzwjK4Zg0CCGkBezWe0pyWIVOXEx8V374TtL6+2LT+TicnXQQolZtrQTOrVyP12qHWvXt4ipLsKudncP7twCMHy4L6HGETcnGsN"
        }
        ```
6. Copy above data and paste them into fields on "2. hedera_executeTransaction"
7. Click "Submit to wallet" and proceed.
    - Now I get a tranactionlist as a parameter as below:
        ```
        transactionList:  Cs4BKssBClUKGgoMCOenibEGELH85qUBEggIABAAGMieLRgAEgYIABAAGAMYgMLXLyICCHgyAHIkCiIKDwoICAAQABjIni0Qzw8YAAoPCggIABAAGPqeLRDQDxgAEnIKcAosMCowBQYDK2VwAyEAeHoJj+SIHKskbwRbar3yhKGchGPm7rCMvPCMrhmDQIIaQF7NZ7SnJYhU5cTHxXfvhO0vr7YtP5OJyddBCiVm2tBM6tXI/Xaoda9e3iKkuwq52dw/u3AIwfLgvocYRNycaw0=
        ```
    - My code for executeTransaction:
        ```js
        byte[] base64DecodedTxBodyBytes = Base64.decode(base64SignedTransaction, Base64.DEFAULT);
        Transaction transaction = Transaction.fromBytes(base64DecodedTxBodyBytes);
        TransactionResponse transactionResponse = (TransactionResponse)  transaction
            .execute(client);
        ```
8. See error
    - Submitted transaction fails with following error.
        > `0.0.741192@1713525845.354746831` failed pre-check with the status `INVALID_SIGNATURE`
     com.hedera.hashgraph.sdk.PrecheckStatusException: Hedera transaction `0.0.741192@1713525845.354746831` failed pre-check with the status `INVALID_SIGNATURE`
    - I attempted these actions in the iOS environment based on hedera-protobufs-swift as well, but encountered the same error.

**Expected behavior** A clear and concise description of what you expected to happen.
The transaction should be submitted successfully.

**Desktop (please complete the following information):**

- OS: [macOS Sonoma 14.2.1]
- Browser [chrome]
- hedera-sdk-java SDK Version [2.29.1]
- grpc-okhttp SDK Version [1.46.0]

**Smartphone (please complete the following information):**

- Device: [Galaxy S24 Ultra]
- OS: [Android 14]

**Additional context** Add any other context about the problem here.
I'll refer to the wallet on https://wc.hgraph.app/ as "example wallet." When conducting the following test using the Dapp on https://wc.hgraph.app/, the issue occurred only when executing the signature map generated from my wallet in my wallet.
1. Executing the transaction singed by my wallet on the example wallet : SUCCESS  → means my wallet sings a transaction fine.
2. Executing the transaction signed by the example wallet on my wallet : SUCCESS → means my wallet executes a signed transaction fine.
3. Executing the transaction signed by the example wallet on the same one : SUCCESS → means the sample wallet works fine in signing and executing transactions.
4. Executing the transaction signed by my wallet on the same one : FAIL (INVALID_SIGNATURE) → No idea for now.

**Comment by franfernandez20** [comment]
We have encountered a similar issue where the signature in the transaction is breaking due to makeTransactionBody. You can find more details about this in the next discussion:

https://github.com/hashgraph/hedera-sdk-js/issues/2218

I believe it would be better to move all of the transaction serialization to the transaction.toBytes() method.

**Comment by soharang** [comment]
@franfernandez20 Thanks for your replying and sharing similar issue. In my case,

**Comment by gregscullard** [comment]
I think the issue is that a Transaction object in the SDK contains multiple actual transactions (HAPI transactions) so that the SDK can deal with node connection failures without prompting for additional signatures.

The wallet connect library expects a single HAPI transaction, not a Transaction. So when you `.toBytes()` a transaction, you're sending a higher level object the wallet connect library, the signature is returns is on the higher level object, not the HAPI transactions within.

Let me look how this can be done with the Java SDK.

For clarity and example

Transaction in the sdk <- This is what you're asking wallet connect to sign
   HAPI Transaction for node 0.0.3
   HAPI Transaction for node 0.0.4 <- this is what you need wallet connect to sign
   HAPI Transaction for node 0.0.5
   HAPI Transaction for node 0.0.6
   HAPI Transaction for node 0.0.7

**Comment by gregscullard** [comment]
This may work

```
//import com.hedera.hashgraph.sdk.AccountId;
//import com.hedera.hashgraph.sdk.PrecheckStatusException;
//import com.hedera.hashgraph.sdk.PrivateKey;
//import com.hedera.hashgraph.sdk.ReceiptStatusException;
//import com.hedera.hashgraph.sdk.TransactionResponse;
//import com.hedera.hashgraph.sdk.TransferTransaction;

import com.hedera.hashgraph.sdk.*;
import io.github.cdimascio.dotenv.Dotenv;

import java.util.Objects;
import java.util.concurrent.TimeoutException;
import java.util.function.Function;

public class CreateSingleTransaction {

  private CreateSingleTransaction() {
  }
  static AccountId OPERATOR_ID = AccountId.fromString(Objects.requireNonNull(Dotenv.load().get("OPERATOR_ID")));
  static PrivateKey OPERATOR_KEY = PrivateKey.fromString(Objects.requireNonNull(Dotenv.load().get("OPERATOR_KEY")));

  public static void main(String[] args) throws PrecheckStatusException, TimeoutException, ReceiptStatusException { //throws TimeoutException, PrecheckStatusException, ReceiptStatusException {
    Client client = Client.forTestnet();

    // Create a dummy key for the client
    PrivateKey dummyKey = PrivateKey.generateED25519();

    client.setOperator(OPERATOR_ID, dummyKey);
    client.setMaxNodesPerTransaction(1);
    Transaction transaction = new TransferTransaction()
            .addHbarTransfer(OPERATOR_ID, Hbar.from(1).negated())
            .addHbarTransfer(AccountId.fromString("0.0.3"), Hbar.from(1))
            .freezeWith(client);
    transaction.signWith(OPERATOR_KEY.getPublicKey(), signer());

    TransactionResponse response = (TransactionResponse) transaction.execute(client);
    response.getReceipt(client);

    System.out.println("done");
  }
  private static Function<byte[],byte[]> signer() {
    //  you'd invoke wallet connect here and get the signature from it
    return (
            t -> OPERATOR_KEY.sign(t)
    );
  }
}
```

replace

```
return (
            t -> OPERATOR_KEY.sign(t)
    );
```
in the signer() function with your implementation of the wallet connect integration

**Comment by gregscullard** [comment]
Note this requires that you know the public key of the wallet being invoked through wallet connect

**Comment by bugbytesinc** [comment]
I don't know about the Java sdk, but with the JavaScript sdk, that only works when the `Transaction` is internally holding only one actual transaction in the `TransactionList`, in other words the `Client` will have needed to have been created with only one node, using the custom `forNetwork([{}])` form.

**Comment by gregscullard** [comment]
In the example above, I set ` client.setMaxNodesPerTransaction(1);` to ensure only one HAPI transaction exists within the Transaction, the SDK will still randomly select from its address book.

The signer is invoked for every inner (HAPI) transaction so the actual bytes of the transaction are signed, not the Transaction. If `setMaxNodesPerTransaction` was set to 10, the signer would be invoked 10 times.

The Javascript SDK also supports the `Signer` method, wonder if that would work with wallet connect (the downside is that you need to know the wallet's public key) with the `.sign` method.

A signer can also be setup at the client level, but again, I think the public key has to be known, the signer only returns a signature which isn't enough for a signature map.

**Comment by gregscullard** [comment]
maybe a signature map with no public key (or prefix) should be accepted if there's only one possible signature...

**Comment by soharang** [comment]
@gregscullard 

Thanks for your guide in detail. I was able to understand what the issue could be.

In order to handle the hedera_signTransaction request, the Wallet does not create a signed Transaction, but rather creates a signed SignatureMap so I am not sure I can set MaxNodesPerTransaction during hedera_signTransaction process.
In my understanding, for 'hedera_signTransaction' method, it requires only SignatureMap type as a return value from signed TransactionBody object so I cannot set  MaxNodesPerTransaction during signing a given TransactionBody and converting to SignatureMap object for return.

For `hedera_executeTransaction`, the sample Dapp on https://wc.hgraph.app converts my providing signature map into TransactionList object. 
Wouldn't it be possible that the sample Dapp might need to set the MaxNodesPerTransaction property when creating the TransactionList?

**Comment by soharang** [comment]
@gregscullard Hello, 

We have resolved the issue. There were two factors causing the 'Invalid Signature' error.

1. During the creation of the signature map, I utilized a public key in DER format, which resulted in an error.
   
2. Prior to signing the transaction body, I inserted the bytes into a TransactionBody proto container using TransactionBody.parseFrom(base64DecodedTxBodyBytes); - I should have directly signed the base64DecodedTxBodyBytes instead."

It would be cool if the team could review the guide for any additions that could prevent encountering such issues.
If the information is already in the guide, I would appreciate it if you could let me know where I can find it.

Thank you.
