### ISSUE TITLE
Hedera Chain Specific Explorer Submission Test Cases on WalletConnect

### ISSUE THREAD

**Issue by soharang** [hashgraph/hedera-wallet-connect#120]
**Is your feature request related to a problem? Please describe.**
There is no Hedera chain specific explorer submission testcases on WalletConnect official guide.
https://docs.walletconnect.com/cloud/explorer-submission#chain-specific

**Describe the solution you'd like** A clear and concise description of what you want to happen.
It would be appreciated if the Hedera WalletConnect Team could liaise with WalletConnect to create Hedera chain specific explorer submission test cases.

**Additional context** Add any other context or screenshots about the feature request here.
Here I share the ticket I created on the WalletConnect official GitHub.
https://github.com/orgs/WalletConnect/discussions/4461

**Comment by kantorcodes** [comment]
Closing in favor of pursuing when when we look at the reown upgrade.
