### ISSUE TITLE
Error: No matching key. history: 1714728659779782

### ISSUE THREAD

**Issue by supermonkeybrainz** [hashgraph/hedera-wallet-connect#126]
Sometimes hedera-wallet-connect will start logging errors in the browser console:

```
 Error: No matching key. history: 1715034600376459
    at Vt.getRecord (x25519.ts:616:1)
    at Vt.get (x25519.ts:616:1)
    at ds.onRelayEventResponse (index.ts:54:1)
    at EventEmitter.<anonymous> (index.ts:54:1)
```

Once this happens the communication between wallets and applications becomes unreliable.  Sometimes the transactions will continue processing as normal, other times the wallets will begin throwing exceptions before the transaction has even been signed (though the transactions will usually still process).  Sometimes the wallet will stop receiving the transaction signature requests.  The only way to overcome this is to disconnect the wallet from the app and close the browser.

Reproducing is not always straightforward.  I am able to do this consistently in the hashconnect react example application.  Just connect your wallet, then try to create a transaction.  See video for example.

https://github.com/hashgraph/hedera-wallet-connect/assets/34159275/323d3290-6247-418d-a436-0c163932afb7

Applications are only as reliable as their wallet interactions.  We need this to work more reliably if we want `hedera-wallet-connect` to be a viable option for app developers.

- OS: Windows
- Browser Chrome, Edge

**Comment by Ashe-Oro** [comment]
+1 seeing this issue as well. Very difficult to reproduce on other machines, but seems to persist on the same machine. 
![image](https://github.com/hashgraph/hedera-wallet-connect/assets/5784328/aa10ce4a-d717-4975-a6da-6c7bd00b8d83)

**Comment by hgraphql** [comment]
This seems to be an expected error that might be able to be handled more efficiently - https://docs.walletconnect.com/web3wallet/wallet-usage#%EF%B8%8F-expected-errors

**Comment by supermonkeybrainz** [comment]
> This seems to be an expected error that might be able to be handled more efficiently - https://docs.walletconnect.com/web3wallet/wallet-usage#%EF%B8%8F-expected-errors

Appreciate the link.  I arrived at a similar conclusion, and determined that the connectivity issues I was seeing were more likely related to `hashconnect` v3 than `hedera-wallet-connect`.  I'll close this issue, as the described error message seems to be pervasive and mostly unavoidable in the world of WalletConnect. 🤷

**Comment by jwtong** [comment]
Same issue for me, keeps coming up

**Comment by phucvarmeta** [comment]
@supermonkeybrainz seem like this issue is on hedera-wallet-connect.

**Comment by phucvarmeta** [comment]
https://www.loom.com/share/2d896a9e4e7c4e6eb6f5f487b2bf0999

**Comment by joelkperkins** [comment]
Just noting for future readers that I also experience this, but want to add that I do not experience this mobile sign in. 

The error triggers whenever I disconnect the wallet from my app.

I am implementing `signAndVerifyWithDAppConnector` now and the same error trigger before the signature is even attempted. 

Again, desktop only. On mobile, the signature works 100%.

Thanks!
