### ISSUE TITLE
Repo rules do not follow agreed up open source guidelines

### ISSUE THREAD

**Issue by tmctl** [hashgraph/hedera-wallet-connect#143]
Our current governance guidelines require 1 approval from SL, 1 approval from Hgraph, and 1 approval from a wallet provider. This sure to update, and we have a process for that.

It is understood that this delineation is not completely possible though github rules, though we can add a requirement for 3+ reviewers, and autoassign the active contributor group to PR's.

For more information: https://github.com/hashgraph/hedera-wallet-connect/wiki/WalletConnect-for-Hedera:-Repository-Governance#pull-request-approvals

If there's a need to update governance, please communicate the updates needed, otherwise please set up the repo to be more favorable for community contribution.

**Comment by hgraphql** [comment]
please autoassign @hashgraph/hedera-wallet-connect-contributors to all PR's moving forward

**Comment by tmctl** [comment]
closing this issue as Hgraph is a code owner and now able effectively manage the repository as agreed upon by contributors
