### ISSUE TITLE
Hedera no longer listed in WalletConnect docs

### ISSUE THREAD

**Issue by hgraphql** [hashgraph/hedera-wallet-connect#160]
https://docs.walletconnect.com/

On the sidebar, the Hedera spec is no longer listed.

**Comment by itsbrandondev** [comment]
WalletConnect has been notified and is looking into it

**Comment by itsbrandondev** [comment]
this will be resolved tomorrow. also we have a request from WalletConnect @hgraphql please see https://github.com/hashgraph/hedera-wallet-connect/issues/171

**Comment by itsbrandondev** [comment]
hedera walletconnect docs have been restored → https://docs.walletconnect.com/advanced/multichain/rpc-reference/hedera-rpc

cc @hgraphql 

closing this issue : )
