### ISSUE TITLE
Add Hedera logo to WalletConnect chain list

### ISSUE THREAD

**Issue by itsbrandondev** [hashgraph/hedera-wallet-connect#171]
WalletConnect has requested that we add the Hedera logo to the chain list

More info: https://docs.walletconnect.com/web3modal/react/options#chainimages

Attached is an example of how Celo looks

![Screenshot 2024-06-11 at 20 05 19](https://github.com/hashgraph/hedera-wallet-connect/assets/95549232/3ced943a-0f92-48c7-b467-274e02280c7a)

**Comment by tmctl** [comment]
@itsbrandondev what are the steps to make this happen?

**Comment by itsbrandondev** [comment]
the platform has changed quite a bit since the original issue was created. i am adding a link to the updated documentation on this: https://docs.walletconnect.com/appkit/vue/core/options#chainimages

**Comment by tmctl** [comment]
closing as the docs show how to set the image explicitly, though I have not found a way to set a "default image" for Hedera in any repo
