### ISSUE TITLE
Critical Dependency

### ISSUE THREAD

**Issue by kevincompton** [hashgraph/hedera-wallet-connect#188]
I'm getting the following when trying to build my Next js application using the hashgraph and hashconnect packages:

./node_modules/@hashgraph/hedera-wallet-connect/dist/node-esm.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

**To Reproduce** Steps to reproduce the behavior:

1. Install and require: "@hashgraph/sdk": "^2.44.0",
    "hashconnect": "^3.0.13",
2. Build the app
3. Notice the warning printed in the build output

**Expected behavior** I'm nnot sure that this is the reason my application fails to build but it is one of the warnings before exiting that I'm trying to address.

**Comment by thedanielmark** [comment]
Having the same issue with my Next.js application.

"@hashgraph/sdk": "^2.41.0"
"hashconnect": "^3.0.13"

**Comment by tmctl** [comment]
this should no longer be an issue with a recent library build

**Comment by jazdevv** [comment]
its still an issue
