### ISSUE TITLE
Error: Cannot find module 'crypto'

### ISSUE THREAD

**Issue by kevincompton** [hashgraph/hedera-wallet-connect#189]
This package is giving my app an error on run, it seems to have a deprecated plugin

1. Install the plugin
2. require it
3. run the environment
4. inspect the trace stack for this error

**Comment by justynspooner** [comment]
I think I'm having a similar issue to you. Please see if [this](https://github.com/hashgraph/hedera-wallet-connect/issues#:~:text=Issues%20list-,NextJS%2014%20app%20fails%20to%20build%20with%20%2D%20Cannot%20find%20module%20%27crypto%27,-%23190%20opened%20now
) is similar to what you're seeing. I've added links to a repo and additional context to help with working out a proper fix.

**Comment by kevincompton** [comment]
> I think I'm having a similar issue to you. Please see if [this](https://github.com/hashgraph/hedera-wallet-connect/issues#:~:text=Issues%20list-,NextJS%2014%20app%20fails%20to%20build%20with%20%2D%20Cannot%20find%20module%20%27crypto%27,-%23190%20opened%20now) is similar to what you're seeing. I've added links to a repo and additional context to help with working out a proper fix.

I'm afraid this link is bad

**Comment by kevincompton** [comment]
So I've looked into this further and it's for sure whats failing my lint. It works fine without it locally but any attempt at a polyfill so far has failed to get rid of the npm error (possibly because it's coming from a sub package). By all accounts you guys shouldn't be using this package for client side applications. In the meantime I'm just going to have to circle back to deploying my app on netlify.

**Comment by justynspooner** [comment]
Apologies, here is the link to the ticket https://github.com/hashgraph/hedera-wallet-connect/issues/190

If you're running an app that uses server side rendering then you can dynamically import the library which should solve the issue you're seeing. Here's an example in a NextJS app:

https://github.com/justynspooner/hedera-wallet-connect-test/blob/c17d3e5aacfc79d1a73c76f9c6b3b127791f30ee/components/HederaWalletConnect.tsx

**Comment by tmctl** [comment]
@kevincompton 

does this PR solve this issue for you : https://github.com/hashgraph/hedera-wallet-connect/pull/224.

You can test by using a pre-release version of the library built off of that PR - `npm i @hashgraph/hedera-wallet-connect@1.3.2-1`

**Comment by tmctl** [comment]
should be complete in v1.3.2

**Comment by tmctl** [comment]
closing as complete, if you are still experiencing issues with the most recent version please feel free to re-open
