### ISSUE TITLE
NextJS 14 app fails to build with - Cannot find module 'crypto'

### ISSUE THREAD

**Issue by justynspooner** [hashgraph/hedera-wallet-connect#190]
# Describe the bug

When running `npm run build` on a brand new NextJS app with a simple import from the `@hashgraph/hedera-wallet-connect`, the app fails to build.

# To Reproduce

Here is a reproducible example of the bug on the `build-issue` branch:
https://github.com/justynspooner/hedera-wallet-connect-test/tree/build-issue

```
node: v22.3.0
NextJS: 14.2.4
@hashgraph/hedera-wallet-connect: 1.2.0
```

Run `npm run build` and see the console error with:

```
> Build error occurred
Error: Failed to collect page data for /
    at /dev/hedera-wallet-connect-test/node_modules/next/dist/build/utils.js:1268:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
```
This error is useless mainly because NextJS isn't surfacing the underlying issue 🤦  We discover the underlying issue when we run in dev mode as described below.

# Expected behavior
The app should build successfully within a new NextJS app.

# Additional Context
When running `npm run dev` the app does run, however there are lots of warnings in the console:

```
○ Compiling / ...
(node:71683) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
 ⚠ ./node_modules/@hashgraph/hedera-wallet-connect/dist/browser-esm.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

Import trace for requested module:
./node_modules/@hashgraph/hedera-wallet-connect/dist/browser-esm.js
./components/HederaWalletConnect.tsx

./node_modules/@hashgraph/hedera-wallet-connect/dist/node-esm.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

Import trace for requested module:
./node_modules/@hashgraph/hedera-wallet-connect/dist/node-esm.js
./components/HederaWalletConnect.tsx
 ⨯ Error: Cannot find module 'crypto'
    at webpackEmptyContext (/Users/justyn/dev/hedera-wallet-connect-test/.next/server/app/page.js:22:10)
    at __webpack_require__ (/Users/justyn/dev/hedera-wallet-connect-test/.next/server/webpack-runtime.js:33:42)
    at eval (./components/HederaWalletConnect.tsx:7:90)
    at (ssr)/./components/HederaWalletConnect.tsx (/Users/justyn/dev/hedera-wallet-connect-test/.next/server/app/page.js:279:1)
    at Object.__webpack_require__ [as require] (/Users/justyn/dev/hedera-wallet-connect-test/.next/server/webpack-runtime.js:33:42)
digest: "2480459522"
 GET / 500 in 1405ms
 ⚠ ./node_modules/@hashgraph/hedera-wallet-connect/dist/browser-esm.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

Import trace for requested module:
./node_modules/@hashgraph/hedera-wallet-connect/dist/browser-esm.js
./components/HederaWalletConnect.tsx

./node_modules/@hashgraph/hedera-wallet-connect/dist/node-esm.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

Import trace for requested module:
./node_modules/@hashgraph/hedera-wallet-connect/dist/node-esm.js
./components/HederaWalletConnect.tsx
 ⚠ ./node_modules/@hashgraph/hedera-wallet-connect/dist/browser-esm.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

Import trace for requested module:
./node_modules/@hashgraph/hedera-wallet-connect/dist/browser-esm.js
./components/HederaWalletConnect.tsx

./node_modules/@hashgraph/hedera-wallet-connect/dist/node-esm.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

Import trace for requested module:
./node_modules/@hashgraph/hedera-wallet-connect/dist/node-esm.js
./components/HederaWalletConnect.tsx
 ⚠ ./node_modules/@hashgraph/hedera-wallet-connect/dist/browser-esm.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

Import trace for requested module:
./node_modules/@hashgraph/hedera-wallet-connect/dist/browser-esm.js
./components/HederaWalletConnect.tsx

./node_modules/@hashgraph/hedera-wallet-connect/dist/node-esm.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```

The `Error: Cannot find module 'crypto'` issue looks like it might stem from this code in the `@hashgraph/sdk` but haven't had time to look into this properly yet.

https://github.com/hashgraph/hedera-sdk-js/blob/482fc3b364bc744dd1b1dd3822baa08251a0130c/packages/cryptography/src/primitive/aes.js#L1

# Current Work Around
To work around the issue, we can dynamically import the `@hashgraph/hedera-wallet-connect` as seen here:
https://github.com/justynspooner/hedera-wallet-connect-test/blob/main/components/HederaWalletConnect.tsx

**Comment by tmctl** [comment]
thanks @justynspooner, with nextjs 14, I believe this error has to do with the change to server components and the complexity involved with that

**Comment by tmctl** [comment]
Here's what our team has found as well:

> The problem is caused by the attempt of Nextjs 14 to use the node version of the package on the frontend side.
> There is no good way to solve this, but you can move the package import to an asynchronous function and call it like that.
> Also in nextConfig you should add `swcMinify: false`
>
> Example of use - init method can be imported into a component and used when pressing a button / initializing a component.

```typescript
import { LedgerId } from "@hashgraph/sdk";

const init = async () => {
  const { HederaJsonRpcMethod, DAppConnector, HederaChainId } = await import(
    "@hashgraph/hedera-wallet-connect"
  );

  const projectId = "your wallet connect project id";
  const metadata: any = {
    name: "App",
    description: "My app",
    url: "https://example.com/",
    icons: ["https://example/logo.png"],
  };

  const dAppConnector = new DAppConnector(
    metadata,
    LedgerId.fromString("testnet"),
    projectId,
    Object.values(HederaJsonRpcMethod),
    [],
    [HederaChainId.Testnet]
  );
  try {
    await dAppConnector.init({ logger: "error" });
    await dAppConnector.openModal();

    //the rest of the logic goes here
    //...
    //...
  } catch (e) {
    await dAppConnector.disconnectAll();
    console.log(e);
  }
};
export default init;
```

**Comment by tmctl** [comment]
@justynspooner @franfernandez20 

from our call, does this problem go away if we just disable minification in esbuild?

If so, I think it makes perfect sense to disable minification as the consumer of the library should be tasked with minification

**Comment by franfernandez20** [comment]
> @justynspooner @franfernandez20
> 
> from our call, does this problem go away if we just disable minification in esbuild?
> 
> If so, I think it makes perfect sense to disable minification as the consumer of the library should be tasked with minification

Yes, in our case, we address the problems by avoiding minification. Disabling it makes sense to me.

**Comment by justynspooner** [comment]
This solution does work although, since the issue is with the minification of the @hashgraph/sdk another option might be to keep the minification but add the @hashgraph/sdk as a peer dependency instead:

```
package.json
…
"peerDependencies": {
    "@hashgraph/sdk": "^2.40.0",
},
…
```

This would have the added benefit of letting the consumer pick the version they would like to use rather than HWC enforcing it.

It would also mean that projects that already use the @hashgraph/sdk for their own services wouldn't have to bundle two different versions.

**Comment by tmctl** [comment]
should be complete in v1.3.2

**Comment by tmctl** [comment]
marking as closed, please feel free to re-open if something was missed

**Comment by jaycoolslm** [comment]
Looks like with 1.3.2 you need to `npm i @walletconnect/modal` (as well as go swcMinify: false) to get this to build correctly

**Comment by jaycoolslm** [comment]
Also looks like bumping up to 1.3.2 and then installing walletconnect/modal fixes all the above issues...
