### ISSUE TITLE
Reduce the bundle size

### ISSUE THREAD

**Issue by justynspooner** [hashgraph/hedera-wallet-connect#191]
# The issue
![Screenshot 2024-07-01 at 16 06 52](https://github.com/hashgraph/hedera-wallet-connect/assets/1853660/b308d72c-f3f5-44bc-aa60-ab25885cf73f)

The bundle size is currently 2.4MB (631.54KB zipped)
https://bundlephobia.com/package/@hashgraph/hedera-wallet-connect@1.2.0

# Describe the solution you'd like

A package which works with modern bundlers to allow for optimisations such as tree shaking to reduce the bundle size as small as possible

# Additional context
This issue heavily relies upon https://github.com/hashgraph/hedera-sdk-js/issues/1719 but wanted to track here as well as Hedera Wallet Connect is likely to get the most benefit from the improvement due to the code predominantly running client side. The faster people can download this package into their browsers, the smoother their experience will be.

**Comment by tmctl** [comment]
the bundler is esbuild which is a modern bundler, though maybe settings need to be changed?

also open to another bundler as well

**Comment by tmctl** [comment]
@justynspooner 

does this PR solve this issue? : https://github.com/hashgraph/hedera-wallet-connect/pull/224.

You can test by using a pre-release version of the library built off of that PR - `npm i @hashgraph/hedera-wallet-connect@1.3.2-1`

I've tested using https://github.com/justynspooner/hedera-wallet-connect-test and seems to do the trick

**Comment by tmctl** [comment]
should be complete in v1.3.2
