### ISSUE TITLE
Improve clarity of set up in documentation

### ISSUE THREAD

**Issue by jaycoolslm** [hashgraph/hedera-wallet-connect#207]
Docs don't have any mention of environment set up e.g. `npm install ___` or `import ___ from '___'`

Would be helpful for new devs to easily figure out what they need to do to get started

**Comment by tmctl** [comment]
hey @jaycoolslm I have some additions to the readme here - https://github.com/hashgraph/hedera-wallet-connect/pull/224

does that help?

**Comment by kantorcodes** [comment]
Hey @jaycoolslm - we have a new PR that will help on this: https://github.com/hashgraph/hedera-wallet-connect/pull/317 

Keen for any feedback you might have.

**Comment by jaycoolslm** [comment]
Apologies for delay, see its already approved. Looks good @kantorcodes
