### ISSUE TITLE
Issue with getRecord Query Failing When Using Hedera Wallet Connect for Stablecoin Creation

### ISSUE THREAD

**Issue by MiguelLZPF** [hashgraph/hedera-wallet-connect#229]
**Describe the bug** A clear and concise description of what the bug is.

We have an issue in the Hedera Stablecoin Studio when creating a new Stablecoin. This process involves more than one transaction and it needs to recover the transaction record from the network before performing the following transaction. Using Hedera Wallet Connect (HWC) is working for signing transactions, but when trying to sign the getRecord query, it fails. Connecting using Blade Wallet directly is working fine.

When connecting using Hedera Wallet Connect and Blade Wallet, the first transaction is signed and sent correctly to the Hedera network, but then the getTxRecord is returning an error:

```bash
Error: Unsupported query type
    at DAppSigner._parseQueryResponse (http://localhost:3000/static/js/bundle.js:131848:13)
    at DAppSigner._tryExecuteQueryRequest (http://localhost:3000/static/js/bundle.js:131862:22)
    at async DAppSigner.call (http://localhost:3000/static/js/bundle.js:131876:25)
    at async HederaTransactionResponseAdapter.getRecord (http://localhost:3000/static/js/bundle.js:104195:20)
    at async HederaTransactionResponseAdapter.manageResponse (http://localhost:3000/static/js/bundle.js:104160:33)
    at async HederaWalletConnectTransactionAdapter.signAndSendTransaction (http://localhost:3000/static/js/bundle.js:106048:14)
    at async HederaWalletConnectTransactionAdapter.contractCall (http://localhost:3000/static/js/bundle.js:103992:12)
    at async HederaWalletConnectTransactionAdapter.create (http://localhost:3000/static/js/bundle.js:103555:14)
    at async CreateCommandHandler.execute (http://localhost:3000/static/js/bundle.js:74902:17)
    at async StableCoinInPort.create (http://localhost:3000/static/js/bundle.js:94106:28)
```

![image](https://github.com/user-attachments/assets/88fba51f-b2cb-4133-9dd8-afb2f099c0c6)

The logs of the history_created events:
![image](https://github.com/user-attachments/assets/055b53e7-2fbe-4d50-b241-08cb094cde85)

![image](https://github.com/user-attachments/assets/be116f40-9ac4-43df-8979-6bf413fc5b13)

And the error that is cached by the stablecoin is "{}" or empty.

When connecting through Blade Wallet directly (No Wallet Connect) we are able to sign the transaction, and the getTxRecord. All working as expected: 

![image](https://github.com/user-attachments/assets/88b703bd-d7a8-44e2-8578-ba94af6670f9)

```bash
getRecordWithSigner
getRecordWithSigner : {"receipt":{"status":"SUCCESS","accountId":null,"filedId":null,"contractId":"0.0.2167166","topicId":null,"tokenId":null,"scheduleId":null,"exchangeRate":{"hbars":30000,"cents":186439,"expirationTime":"2024-08-01T12:00:00.000Z","exchangeRateInCents":6.2146333333333335},"topicSequenceNumber":"0","topicRunningHash":"","totalSupply":"0","scheduledTransactionId":null,"serials":[],"duplicates":[],"children":[]},"transactionHash":"35ed5c5104e88e6b8ac4de8eb2e8b21ae558d3947f029ab659452a6621904a2225d8c1682d9a5c35f0f8feb87da68273","consensusTimestamp":"2024-08-01T11:47:25.217Z","transactionId":"0.0.3990677@1722512820.565148273","transactionMemo":"","transactionFee":"274000000","transfers":[{"accountId":"0.0.98","amount":"1857485518","isApproved":false},{"accountId":"0.0.3990677","amount":"-1857485518","isApproved":false}],"tokenTransfers":{},"tokenTransfersList":[],"scheduleRef":null,"assessedCustomFees":[],"nftTransfers":{},"automaticTokenAssociations":[],"parentConsensusTimestamp":null,"aliasKey":null,"duplicates":[],"children":[],"ethereumHash":"","paidStakingRewards":[],"prngBytes":null,"prngNumber":null,"evmAddress":null}
```

**To Reproduce** Steps to reproduce the behavior:

1. Clone the Hedera Stablecoin repository (branch feat/hedera-wallet-connect)
2. Setup Stablecoin with a similar .env in the WEB module:
    ``` env
    # Log level for the application. The default value is ERROR.
    # Acceptable values are ERROR, WARN, INFO, HTTP, VERBOSE, DEBUG and SILLY in order of priority (highest to lowest).
    REACT_APP_LOG_LEVEL=DEBUG
    # JSON array with a factory id in Hedera format `0.0.XXXXX` per environment.
    REACT_APP_FACTORIES='[{"Environment":"testnet","STABLE_COIN_FACTORY_ADDRESS":"0.0.2167166"}]'
    # The var must be a unique mirror node service for Hedera network, and this is the service which would be used when the UI starts. If the service doesn't require an API key to authorize requests, the API_KEY and HEADER properties must remain empty.
    REACT_APP_MIRROR_NODE='[{"Environment":"testnet","BASE_URL":"https://testnet.mirrornode.hedera.com/api/v1/", "API_KEY": "", "HEADER": ""}]'
    # The var must be a unique RPC node service for Hedera network, and this is the service which would be used when the UI starts. If the service doesn't require an API key to authorize requests, the API_KEY and HEADER properties must remain empty.
    REACT_APP_RPC_NODE='[{"Environment":"testnet","BASE_URL":"https://testnet.hashio.io/api", "API_KEY": "", "HEADER": ""}]'
    # This is a proprietary Create React App configuration. You can read more information in its documentation.[Create React App documentation](https://create-react-app.dev/docs/advanced-configuration/)
    GENERATE_SOURCEMAP=true
    REACT_APP_SHOW_CONFIG=true
    REACT_APP_PROJECT_ID='8fc26370383a50de1c3bd638d334292e'
    REACT_APP_DAPP_NAME='StableCoin'
    REACT_APP_DAPP_DESCRIPTION='StableCoin is a decentralized stablecoin platform built on Hedera Hashgraph.'
    REACT_APP_DAPP_URL='https://wc.hgraph.app/'
    REACT_APP_DAPP_ICONS=['https://stablecoinstudio.com/static/media/hedera-hbar-logo.4fd73fb360de0fc15d378e0c3ebe6c80.svg']
    ```
3. Use a Wallet Connect to login using Blade Wallet
4. Create a new Stablecoin (plus icon un the top bar)
5. Verification exception should be thrown

**Expected behavior** A clear and concise description of what you expected to happen.

Should create new stablecoin as when connecting directly.

**Screenshots** If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

- OS: MacOS and Linux
- Browser: Chrome
- Version: 127.0

**Additional context** Add any other context about the problem here.

**Comment by hgraphql** [comment]
thank you for the detailed report @MiguelLZPF

**Comment by AlbertoMolinaIoBuilders** [comment]
To be more precise, this is the line of code within the stablecoin studio that is returning the error : 

`const record = await transactionResponse.getRecordWithSigner(signer);
`

- **transactionResponse** => TransactionResponse object from @hashgraph/sdk@2.40.0

- **signer** => Signer object from @hashgraph/sdk@2.40.0. It is the first signer from the "_dAppConnector_" object imported from @hashgraph/hedera-wallet-connect@1.3.2 
```
this.dAppConnector = new DAppConnector(
				this.dappMetadata,
				LedgerId.TESTNET,
				this.projectId,
			);
this.signer = this.dAppConnector.signers[0];
```

**Comment by tmctl** [comment]
@MiguelLZPF @AlbertoMolinaIoBuilders making a note that the referenced stablecoin studio branch is using a wc connection method that has been deprecated by wallet connect. We will remove it in a future release though has been kept in there as to not add breaking changes.

**Comment by MiguelLZPF** [comment]
@tmctl Thank you for looking into it! We used this method because the other one wasn't working for us, but we appreciate the heads up. We'll try to test with the openModal method. The connectQR method we are using isn't flagged as deprecated (@deprecated), so it's hard to know that. It shouldn't influence this particular issue though.

**Comment by tmctl** [comment]
@MiguelLZPF thanks, if you're able to get that working in the stablecoin studio branch, that will better help me to test this issue

@MiguelLZPF @AlbertoMolinaIoBuilders There's also this method to get the signer - https://github.com/hashgraph/hedera-wallet-connect/blob/c59a9ad3333b15b027a0260b63961a7c2327af99/src/lib/dapp/index.ts#L173

it's possible a different signer is being returned in your flow when using a the first in the array.

**Comment by MiguelLZPF** [comment]
Hi @tmctl, quick update on this. Following your advice we changed to getSigner() and it is returning the same signer object. The signer itself seems to be OK since it is dAppSigner and a Signer (hedera signer) as well. But when trying to `response.getRecordWithSigner(signer)` it gets there and does nothing...

**Comment by MiguelLZPF** [comment]
Hello, testing a bit deeper, we catch the specific error from DAppSigner, let us know what you think. The complete trace is added to the description of this issue also.

```bash
Error: Unsupported query type
    at DAppSigner._parseQueryResponse (http://localhost:3000/static/js/bundle.js:131848:13)
    at DAppSigner._tryExecuteQueryRequest (http://localhost:3000/static/js/bundle.js:131862:22)
    at async DAppSigner.call (http://localhost:3000/static/js/bundle.js:131876:25)
```

**Comment by teacoat** [comment]
@MiguelLZPF Is there a reason you arent doing like TransactionResponse.getRecord() just on the dapp? https://docs.hedera.com/hedera/sdks-and-apis/sdks/transactions/get-a-transaction-record#methods

**Comment by MiguelLZPF** [comment]
Hey @teacoat I don't really get your question, we are getting the record just like you referenced, using the SDK on the dApp, the `TransactionResponse.getRecordWithSigner(signer)` variant, but it is the same 🤔
