### ISSUE TITLE
Vanilla javascript example and documentation

### ISSUE THREAD

**Issue by louweal** [hashgraph/hedera-wallet-connect#236]
The Readme says: _"This repository includes a vanilla html/css/javascript implementation with a dApp and wallet example useful for testing and development while integrating WalletConnect and Hedera."_ But there is only a React example? A vanilla javascript example would be very much appreciated since only 5% of websites use React.

The readme also says: _'Use a QR code scanning library to scan and obtain the URI'_. Please give the reader some pointers where to start. Or even better, include it in the example.

I really appreciate the work of the Hedera team, however currently I feel like can't migrate from hashconnect to this method, because the overall documentation feels incomplete and examples seem to be missing.

**Comment by kantorcodes** [comment]
> The Readme says: _"This repository includes a vanilla html/css/javascript implementation with a dApp and wallet example useful for testing and development while integrating WalletConnect and Hedera."_ But there is only a React example? A vanilla javascript example would be very much appreciated since only 5% of websites use React.
> 
> The readme also says: _'Use a QR code scanning library to scan and obtain the URI'_. Please give the reader some pointers where to start. Or even better, include it in the example.
> 
> I really appreciate the work of the Hedera team, however currently I feel like can't migrate from hashconnect to this method, because the overall documentation feels incomplete and examples seem to be missing.

Hey @louweal we recently updated the documentation here: https://hwc-docs.hgraph.app/demos

Could you let me know if this helps you out?

**Comment by kantorcodes** [comment]
Hey @louweal I am closing this issue out for now. Feel free to raise another one if you run into more inquiries about the docs. Thank you for chiming in :)
