### ISSUE TITLE
dAppConnector.init({}) throws error on mount

### ISSUE THREAD

**Issue by jwtong** [hashgraph/hedera-wallet-connect#291]
https://github.com/hashgraph/hedera-wallet-connect/blob/6568206ed5c821ded456601b47d4db12ec3d3168/src/lib/dapp/index.ts#L157

Reproduction Instructions:
1. Connect a HashPack wallet to https://www.saucerswap.finance/
2. Close https://www.saucerswap.finance/ browser
3. Open HashPack extension, disconnect SaucerSwap 
4. Open https://www.saucerswap.finance/, error is thrown, breaks initialization flow on SaucerSwap's React app

Error Details:
1. Since the session was deleted outside the app, the init function does find a session + topic. However, it immediately then fires a `session_delete` event, syncing with the state of the wallet that was already disconnected via HashPack extension.
2. library says "Dapp: Session deleted by wallet!"
3. `this.disconnect(pairing.topic)` throws an error, since the wallet is attempting to disconnect a topic that no longer exists

See below for the error flow

<img width="1172" alt="Screenshot 2024-10-07 at 7 12 46 PM" src="https://github.com/user-attachments/assets/8465d0ea-ae77-4d7b-bc8f-38640a059e35">

One quick/dirty solution would be to try/catch `this.disconnect(pairing.topic)`, but not sure what the best way is

**Comment by teacoat** [comment]
yeah the lib shouldnt be trying to delete that session, just syncing the sessions after the event

**Comment by tmctl** [comment]
@teacoat @jwtong should is it as simple as this? https://github.com/hashgraph/hedera-wallet-connect/pull/299/files

**Comment by tmctl** [comment]
also, seems like this is related? https://github.com/hashgraph/hedera-wallet-connect/issues/281

**Comment by jwtong** [comment]
@tmctl 

I think it would be better to try/catch a disconnect

**Comment by tmctl** [comment]
@jwtong how about this - https://github.com/hashgraph/hedera-wallet-connect/pull/302

**Comment by tmctl** [comment]
@teacoat also linked you to a review based on your comment - https://github.com/hashgraph/hedera-wallet-connect/pull/302
