### ISSUE TITLE
Signer not working in executeWithSigner() method

### ISSUE THREAD

**Issue by lorentsinani** [hashgraph/hedera-wallet-connect#341]
It is working perfectly when using hashconnect library but when with hedera-wallet-connect there is an error while trying to execute a transaction made with ContractExecuteTransaction from hashgraph/sdk.

Here is the error:
Error: Error executing transaction or query:
{
  "txError": {
    "message": "Internal error"
  },
  "queryError": {
    "name": "Error",
    "message": "(BUG) Query.fromBytes() not implemented for type getByKey",
    
   
   
Also tried another solution:

const signedTransaction = await signer.signTransaction(transaction)
      const response = await signedTransaction.execute(client);
      
      
StatusError: transaction 0.0.7520909@1731681701.009052807 failed precheck with status INVALID_SIGNATURE against node account id 0.0.31

**Comment by kantorcodes** [comment]
> It is working perfectly when using hashconnect library but when with hedera-wallet-connect there is an error while trying to execute a transaction made with ContractExecuteTransaction from hashgraph/sdk.
> 
> Here is the error: Error: Error executing transaction or query: { "txError": { "message": "Internal error" }, "queryError": { "name": "Error", "message": "(BUG) Query.fromBytes() not implemented for type getByKey",
> 
> Also tried another solution:
> 
> const signedTransaction = await signer.signTransaction(transaction) const response = await signedTransaction.execute(client);
> 
> StatusError: transaction 0.0.7520909@1731681701.009052807 failed precheck with status INVALID_SIGNATURE against node account id 0.0.31

Hi! 

Could you try with the latest canary release? Also, could you provide a sample of the full transaction you're trying to execute? 

```
   "@hashgraph/hedera-wallet-connect": "1.3.8-canary.25ba652.0",
```

**Comment by lorentsinani** [comment]
Hey,

I believe I found out what the problem is, it is more like a mistake in the error being returned but will see if I can reproduce it with this solution you sent. 

Transaction:

      const transaction = new ContractExecuteTransaction()
        .setContractId(contractId)
        .setGas(100000)
        .setFunction('withdraw', new ContractFunctionParameters().addUint256(tinybarAmount))
        .setNodeAccountIds([AccountId.fromString(nodeId)])
        .setTransactionId(transactionId)
        .freeze(client)

**Comment by kantorcodes** [comment]
> Hey,
> 
> I believe I found out what the problem is, it is more like a mistake in the error being returned but will see if I can reproduce it with this solution you sent.
> 
> Transaction:
> 
> ```
>   const transaction = new ContractExecuteTransaction()
>     .setContractId(contractId)
>     .setGas(100000)
>     .setFunction('withdraw', new ContractFunctionParameters().addUint256(tinybarAmount))
>     .setNodeAccountIds([AccountId.fromString(nodeId)])
>     .setTransactionId(transactionId)
>     .freeze(client)
> ```

Could you provide the contract id? Also, is this in testnet?

**Comment by lorentsinani** [comment]
Yes, no its in mainnet. 

Here you have the `contractId = 0.0.7548629`

**Comment by kantorcodes** [comment]
Thanks! Testnet would be more ideal if possible. Let me know how the new canary version of the SDK goes.

**Comment by kantorcodes** [comment]
@lorentsinani were you able to try the new canary release?

**Comment by lorentsinani** [comment]
> @lorentsinani were you able to try the new canary release?

No, not really. Were busy with some rust smart contracts but while I figured out how to handle that error I believe its okay. I will try it when I get some work done. Thank you for your support btw. Take care!

**Comment by lorentsinani** [comment]
> > > @lorentsinani were you able to try the new canary release?
> > 
> > 
> > No, not really. Were busy with some rust smart contracts but while I figured out how to handle that error I believe its okay. I will try it when I get some work done. Thank you for your support btw. Take care!
> 
> No problem! I'll be closing this issue for now then

Okay no problem, thank you for your support :)
