### ISSUE TITLE
Does not work for react native applications?

### ISSUE THREAD

**Issue by Dav-Webber** [hashgraph/hedera-wallet-connect#376]
**Describe the bug** A clear and concise description of what the bug is.

**To Reproduce** Steps to reproduce the behavior:

**Expected behavior** A clear and concise description of what you expected to happen.

**Screenshots** If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context** Add any other context about the problem here.

**Comment by tmctl** [comment]
@Dav-Webber here's an example - does this repo work for you? https://github.com/hgraph-io/react-native-template

**Comment by Dav-Webber** [comment]
Hey yeah thanks, although when running seem to be getting this error, ios
simulator using expo
 [image: Screenshot 2024-12-13 at 21.32.37.png]

**Comment by Dav-Webber** [comment]
Hey, i come from a .net background, but ive noticed the tooling and sdks
for .net are very bad or non existent. Im happy to learn and work with js
if that is the best sdk for front end stuff, but would be great to have
something like this working and up to date. tried updating stuff and now
getting these errors. What do i need to know to fix this?
[image: Screenshot 2024-12-13 at 21.55.41.png][image: Screenshot 2024-12-13
at 21.55.59.png][image: Screenshot 2024-12-13 at 21.56.19.png]

**Comment by tmctl** [comment]
hey @Dav-Webber I'm not actually seeing the screenshots populate in github

**Comment by tmctl** [comment]
@Dav-Webber please see https://github.com/hashgraph/hedera-wallet-connect/pull/385

Does this help?
