### ISSUE TITLE
Missing types

### ISSUE THREAD

**Issue by teacoat** [hashgraph/hedera-wallet-connect#41]
Importing into a typescript project and you are met with an error about types:

TS7016: Could not find a declaration file for module '@hashgraph/hedera-wallet-connect/dist/node-esm.js'. 'node_modules/@hashgraph/hedera-wallet-connect/dist/node-esm.js' implicitly has an 'any' type.
Try `npm i --save-dev @types/hashgraph__hedera-wallet-connect` if it exists or add a new declaration (.d.ts) file containing `declare module '@hashgraph/hedera-wallet-connect/dist/node-esm.js';`

It seems as though there is no types file
![image](https://github.com/hashgraph/hedera-wallet-connect/assets/3913019/86b7aaff-889f-4b99-85c6-2bdff9fe4761)

![image](https://github.com/hashgraph/hedera-wallet-connect/assets/3913019/11a4d062-b449-44b9-810e-bec15f4e974f)

**Comment by hgraphql** [comment]
@teacoat looks like the dist/types folder did not get published
