### ISSUE TITLE
Weird dependency

### ISSUE THREAD

**Issue by teacoat** [hashgraph/hedera-wallet-connect#42]
This dependency:
![image](https://github.com/hashgraph/hedera-wallet-connect/assets/3913019/79e1e307-75d3-4acd-ab7c-04da460dda29)

Is causing a copy of this repo to be inserted into node_modules

![image](https://github.com/hashgraph/hedera-wallet-connect/assets/3913019/adeeeda6-1698-4ee0-8dc8-103022cae52e)

**Comment by hgraphql** [comment]
@teacoat this is a strategy to run the example with the current codebase while developing

one could also import from the most recently published SDK and the dependency would look the same.

Anyways, this dependency is wrong and should be `@hashgraph/hedera-wallet-connect` as that was the name that was landed on.

In terms of separating out an example using the library, that is totally okay if that's preferred. We'd want to have a spot for a demo / example to live. (maybe this demo gets removed in favor of a demo in the wallet connect repos)

**Comment by teacoat** [comment]
The examples should be using the published package, or at least importing it using npm link, in order to test things in a prod-like situation so you dont run into things like the missing types issue
