### ISSUE TITLE
Please add me as reviewer

### ISSUE THREAD

**Issue by teacoat** [hashgraph/hedera-wallet-connect#44]
Tyler from HashPack here, please add me as a reviewer

**Comment by rajesuwerps** [comment]
Raj from Dropp. Please add me as a reviewer. Thanks.

**Comment by bugbytesinc** [comment]
Jason from Calaxy, please add me as a reviewer as well, Thanks.

**Comment by valeraOlexienko** [comment]
Valera from Blade Labs here, please add me as a reviewer 🙂

**Comment by hgraphql** [comment]
Please add Fran from Kabila as well - https://github.com/hashgraph/hedera-wallet-connect/issues/45

**Comment by gregscullard** [comment]
Ticket created for the repo to be updated with 4 sign offs / approvals on PRs.

**Comment by hgraphql** [comment]
@teacoat @rajesuwerps @valeraOlexienko @franfernandez20

Have you received & accepted invites to the team - hedera-wallet-connect-reviewers

**Comment by franfernandez20** [comment]
> @teacoat @rajesuwerps @valeraOlexienko @franfernandez20
> 
> Have you received & accepted invites to the team - hedera-wallet-connect-reviewers?

Hello @hgraphql, apologies for the delay in my response. I did not receive any invitation.

**Comment by rajesuwerps** [comment]
I remember requesting to add my name but don’t recall getting the invite
after. But I can go back and check if needed.

Regards, Raj

**Comment by hgraphql** [comment]
looks like everybody in this issue has been added and accepted, thanks!
