### ISSUE TITLE
Request to be added as a reviewer.

### ISSUE THREAD

**Issue by franfernandez20** [hashgraph/hedera-wallet-connect#45]
I'm Fran from Kabila. I would like to request to be added as a reviewer.

**Comment by hgraphql** [comment]
Hi @franfernandez20 thanks!

I'm going to close this issue as I've commented over here https://github.com/hashgraph/hedera-wallet-connect/issues/44#issuecomment-1919351119

I had said create a new issue, though seems like it'll be easiest the repo admins to have everybody in 1 ticket.
