### ISSUE TITLE
Remove @walletconnect/qr-modal as it is a deprecated v1 library

### ISSUE THREAD

**Issue by hgraphql** [hashgraph/hedera-wallet-connect#53]
**Is your feature request related to a problem? Please describe.** This library currently has a deprecated WalletConnect library installed. We should remove it in favor of the v2 sdks.

**Describe the solution you'd like** Remove @walletconnect/qr-modal and references in the code

**Additional context** [Web3Modal](https://docs.walletconnect.com/web3modal/about) is the up to date library which is also included in this library, so we just need to remove the old reference & usage.

**Comment by hgraphql** [comment]
my team is going to take this one, should be fairly straightforward

**Comment by tmctl** [comment]
closing this issue this would be part of a larger update
