### ISSUE TITLE
Issue with hedera-wallet-connect and Hashpack Integration

### ISSUE THREAD

**Issue by marelh02** [hashgraph/hedera-wallet-connect#61]
Hello, I am trying to use hedera-wallet-connect to link a demo DApp with hashpack, it doesn't even fail, the connection promise stays pending.

The modal does open, I chose hashpack from the desktop connection section, it takes me to hashpack website (extension does not open), I log in, then nothing happens, I see only my transactions history, I think normally I should be prompted to accept or reject the connection with the DApp.

To reproduce the behavior:
- I created a walletconnect account with a new project and everything needed
- I initiated a walletconnect project with Next JS using the npx commande given in walletconnect cloud (comes with next v13 and the old pages router by default)
- I initiated a NextJS 14 project and took what I need from the previous one (dependencies and env vars)
- I used the example code given in hedera-wallet-connect for inspiration (written in vanilla TS and HTML but adapted it to react), it's a simple button that opens the modal and tries to call the connect method.
- Then I try to connect to hashpack desktop and the problem happens I log in in hashpack and nothing happens

I linked my testnet account to hashpack as the DApp uses the testnet.

![image](https://github.com/hashgraph/hedera-wallet-connect/assets/97633566/339adfa1-a392-4696-a941-73afff05e52b)

Also a websockets error that says the frame header is invalid appears, but I think it's irrelevant, since I get it in the walletconnect template project, and metamask connects just fine

![image](https://github.com/hashgraph/hedera-wallet-connect/assets/97633566/10aee3b0-9ea1-419b-88c7-a52c38e90b87)

I tried to solve the websockets problem with ngrok static domaine, I verified my domaine succefully, as a solved issue here suggested to verify your domaine in walletconnect cloud, but the websockets error still appears: https://github.com/orgs/WalletConnect/discussions/3442

Any insights or assistance in resolving this issue would be greatly appreciated.

Thank you.

- OS: Windows 10
- Browser: Brave v1.62.162

**Comment by marelh02** [comment]
here is the mentioned web sockets error
![image](https://github.com/hashgraph/hedera-wallet-connect/assets/97633566/c78c3aaa-fe59-425c-af89-96f0fbe5082e)

**Comment by hgraphql** [comment]
Hi @marelh02

Are you able to share a repo with the example code from above to help us better trouble shoot?

Thanks

**Comment by marelh02** [comment]
Hello, thanks for the reply, here is the code in question: https://github.com/marelh02/hhmsam_n14/tree/master
you need to set the env variables.

**Comment by marelh02** [comment]
Hello, I have an update about this issue: the websockets error in my computer is something serious, it prevents any dapp (i.e;  1inch and other DEXs ) including those based on the Hedera ecosystem from using walletconnect, when I accessed the demo app from my friends computers, I managed to connect blade wallet (with a testnet account) to it using QR code scan. However, the issue with hashpack still persists sadly, I can't connect from my desktop (they take me to hashpack website and nothing happens). That doesn't mean everything works with Blade, I caught another problem that doesn't belong here, i'll post it in another issue.

**Comment by hgraphql** [comment]
@teacoat do you have any additional information regarding this error that might help us debug?

**Comment by teacoat** [comment]
We haven't really done a ton of testing around this method of pairing - from the wallet list in the connect modal - its on my list to look into

**Comment by yashsisodiya** [comment]
Facing Same issue

**Comment by teacoat** [comment]
This method of pairing works as expected now, closing issue
