### ISSUE TITLE
Add "Wiki" to the Hedera WalletConnect Repository

### ISSUE THREAD

**Issue by itsbrandondev** [hashgraph/hedera-wallet-connect#81]
The WalletConnect Working Group for Hedera has outlined a simple governance structure specific to the management of this repository. Developers are looking to make contributions to the repository will need access to this information. Wallet providers will also need this information to effectively help guide the ongoing maintenance and development of WalletConnect for Hedera.

The group has planned to host this on the "Wiki" of this repository. Can we enable this feature so the information can be added and made accessible?

An alternative could be hosting it separately, but ideally it should be included with this repo.

**Comment by hgraphql** [comment]
@itsbrandondev I think we'll have to ping someone as well

**Comment by itsbrandondev** [comment]
the Wiki has been enabled by @Ashe-Oro and i posted the governance document 👍

https://github.com/hashgraph/hedera-wallet-connect/wiki/WalletConnect-for-Hedera:-Repository-Governance
