### ISSUE TITLE
Error "Cannot find module 'crypto'" when using hedera-wallet-connect

### ISSUE THREAD

**Issue by TKarima22** [hashgraph/hedera-wallet-connect#95]
Hello,
I am using hedera-wallet-connect and I encounter an error related to a missing module 'crypto' when attempting to run the application, 

<img width="953" alt="Screenshot 2024-03-25 at 10 21 41" src="https://github.com/hashgraph/hedera-wallet-connect/assets/98661875/a9454f37-7f74-4c3d-aad5-2eb3399402fb">

<img width="942" alt="Screenshot 2024-03-25 at 10 22 19" src="https://github.com/hashgraph/hedera-wallet-connect/assets/98661875/3aecfbd4-0e12-4d77-bd26-54dd8d3bfd28">

**Steps to Reproduce:**
Run the application using the provided setup.
Navigate to the login page.(the error occurs on every page using hedera-wallet-connect under the hood, not only login)
Observe the error message stating "Cannot find module 'crypto'".

**Additional Information:**
This issue seems to be related to the hedera-wallet-connect library and also same behavior when using hashconnect .

**Environment:**
Node.js Version: v21.7.1
NextJS Version: 14.1.0
hedera-wallet-connect Version: 1.0.6
hashconnect Version: 3.0.13

Please let me know if further information or assistance is required to address this issue.

Thank you.

**Comment by oynozan** [comment]
Downgrading Hashconnect to "^0.2.4" worked, but I don't think that's a suitable solution.

**Comment by TKarima22** [comment]
@oynozan I attempted before to resolve the problem by using that solution, but it resulted in the loss of features that I need, which are present in versions beyond 3.0.0

**Comment by oynozan** [comment]
I faced with the same problem when I downgraded, so it's not a suitable solution as I mention.

**Comment by glitch-txs** [comment]
could be an SSR issue, could you share a repro?

**Comment by justynspooner** [comment]
I've had the same issue here (forgot to search for similar issues before submitting it 🙈): https://github.com/hashgraph/hedera-wallet-connect/issues/190

There's a repo linked in the issue.

**Comment by glitch-txs** [comment]
just try using dynamic imports with [ssr disabled](https://nextjs.org/docs/pages/building-your-application/optimizing/lazy-loading#with-no-ssr), or installing a crypto pollyfill as dep.

**Comment by justynspooner** [comment]
> just try using dynamic imports with [ssr disabled](https://nextjs.org/docs/pages/building-your-application/optimizing/lazy-loading#with-no-ssr), or installing a crypto pollyfill as dep.

You're right, this does resolve the issue. There's an example of it mentioned at the bottom of the description in ticket #190 for anyone else reading this.

For anyone coming to this repo using something like NextJS we should be able to handle this at the library level and have full support for SSR built in like a lot of other libraries are currently offering. Then there wouldn't be a need to dynamically import.

**Comment by glitch-txs** [comment]
> For anyone coming to this repo using something like NextJS we should be able to handle this at the library level and have full support for SSR built in like a lot of other libraries are currently offering. Then there wouldn't be a need to dynamically import.

Yes, you could check if window is defined before executing any browser dependant function 👍

**Comment by tmctl** [comment]
@TKarima22 does this PR solve this issue for you : https://github.com/hashgraph/hedera-wallet-connect/pull/224.

You can test by using a pre-release version of the library built off of that PR - `npm i @hashgraph/hedera-wallet-connect@1.3.2-1`

**Comment by tmctl** [comment]
closing as completed in v1.3.2. If you're still experiencing issues please feel free to re-open
